GenerateOverarchingPlot:
  name: "Generate Overarching Plot"
  description: >
    Create a high-level storyline with multiple endings and branching paths
    based on the initial game prompt.
  expected_output: >
    A plot_outline detailing the overarching story, key branches, and possible endings.
  agent: "PlotMasterAgent"
  output_file: "plot_outline.yaml"
  # No context needed because it doesn't depend on any prior tasks.

CreateNarrativeMap:
  name: "Create Narrative Map"
  description: >
    Transform the plot outline into a structured map of scenes, detailing how
    each scene connects, the branching paths, and any special requirements to progress.
  expected_output: >
    A narrative_tree that shows scenes, transitions, puzzle/door locks, and
    the items or conditions required to unlock them.
  agent: "NarrativeArchitectAgent"
  context:
    - "GenerateOverarchingPlot"
  output_file: "narrative_map.yaml"
  dependencies:
    - "GenerateOverarchingPlot"

DesignArtifactsAndPuzzles:
  name: "Design Artifacts, Puzzles, Monsters, and NPCs"
  description: >
    Based on the narrative map, create a comprehensive list of interactive elements
    (artifacts, puzzles, monsters, NPCs), detailing mechanics and how they tie into
    the story progression.
  expected_output: >
    A puzzle_design document with puzzle mechanics, prerequisites, required artifacts,
    monster and NPC roles, and how each is embedded in the game world.
  agent: "PuzzleSmithAgent"
  context:
    - "CreateNarrativeMap"
  output_file: "puzzle_design.yaml"
  dependencies:
    - "CreateNarrativeMap"

WriteSceneDescriptionsAndDialogue:
  name: "Write Scene Descriptions and Dialogue"
  description: >
    Provide immersive, detailed text for each scene, along with any relevant
    dialogue lines for NPCs or other interactive elements, ensuring consistency
    with puzzles and artifacts.
  expected_output: >
    A scene_texts compilation that includes descriptive prose for each location,
    dialogues, and narrative cues for in-game events.
  agent: "CreativeScribeAgent"
  context:
    - "DesignArtifactsAndPuzzles"
  output_file: "scene_texts.yaml"
  dependencies:
    - "DesignArtifactsAndPuzzles"

CreateGameMechanicsPRD:
  name: "Create Game Mechanics PRD"
  description: >
    Draft a product requirements document specifying how the mechanics, stats,
    combat, and other systems will function in the final game.
  expected_output: >
    A prd_document outlining all core mechanics, skill progression, combat rules,
    and any relevant implementation details.
  agent: "MechanicsGuruAgent"
  context:
    - "WriteSceneDescriptionsAndDialogue"
  output_file: "prd_document.yaml"
  dependencies:
    - "WriteSceneDescriptionsAndDialogue"
