"""
YAML Post-Processor Utility

This module provides utilities to clean and validate YAML files generated by LLMs.
Specifically handles the common issue of LLMs wrapping YAML content in markdown code blocks.
"""

import logging
import re
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)


def strip_markdown_yaml_blocks(content: str) -> str:
    """
    Strip markdown code block markers from YAML content.

    LLMs often wrap YAML in markdown code blocks like:
    ```yaml
    content: here
    ```

    This function removes those markers to produce clean YAML.

    Args:
        content: Raw content that may contain markdown markers

    Returns:
        Clean YAML content without markdown markers
    """
    # Remove leading ```yaml or ``` markers
    content = re.sub(r'^```ya?ml\s*\n', '', content, flags=re.MULTILINE)
    content = re.sub(r'^```\s*\n', '', content, flags=re.MULTILINE)

    # Remove trailing ``` markers
    content = re.sub(r'\n```\s*$', '', content, flags=re.MULTILINE)
    content = re.sub(r'^```\s*$', '', content, flags=re.MULTILINE)

    return content.strip()


def process_yaml_file(filepath: Path, backup: bool = True) -> bool:
    """
    Process a YAML file to remove markdown code block markers.

    Args:
        filepath: Path to the YAML file to process
        backup: Whether to create a .bak backup file

    Returns:
        True if file was processed successfully, False otherwise
    """
    try:
        if not filepath.exists():
            logger.warning(f"File does not exist: {filepath}")
            return False

        # Read original content
        original_content = filepath.read_text()

        # Check if it needs processing (contains markdown markers)
        if '```' not in original_content:
            logger.debug(f"File {filepath.name} does not contain markdown markers, skipping")
            return True

        # Process content
        cleaned_content = strip_markdown_yaml_blocks(original_content)

        # Create backup if requested
        if backup and cleaned_content != original_content:
            backup_path = filepath.with_suffix(filepath.suffix + '.bak')
            backup_path.write_text(original_content)
            logger.info(f"Created backup: {backup_path}")

        # Write cleaned content
        if cleaned_content != original_content:
            filepath.write_text(cleaned_content)
            logger.info(f"Processed {filepath.name}: removed markdown markers")
            return True
        else:
            logger.debug(f"File {filepath.name} unchanged after processing")
            return True

    except Exception as e:
        logger.error(f"Error processing {filepath}: {e}")
        return False


def process_yaml_directory(directory: Path, pattern: str = "*.yaml", backup: bool = True) -> dict:
    """
    Process all YAML files in a directory.

    Args:
        directory: Directory containing YAML files
        pattern: Glob pattern for matching files
        backup: Whether to create backup files

    Returns:
        Dictionary with processing statistics
    """
    stats = {
        'total': 0,
        'processed': 0,
        'failed': 0
    }

    if not directory.exists():
        logger.warning(f"Directory does not exist: {directory}")
        return stats

    yaml_files = list(directory.glob(pattern))
    stats['total'] = len(yaml_files)

    logger.info(f"Processing {stats['total']} YAML files in {directory}")

    for filepath in yaml_files:
        try:
            if process_yaml_file(filepath, backup=backup):
                stats['processed'] += 1
            else:
                stats['failed'] += 1
        except Exception as e:
            logger.error(f"Failed to process {filepath}: {e}")
            stats['failed'] += 1

    logger.info(f"Processing complete: {stats['processed']} processed, {stats['failed']} failed")
    return stats


def validate_yaml_content(content: str) -> tuple[bool, str | None]:
    """
    Validate that content is valid YAML (basic check).

    Args:
        content: YAML content to validate

    Returns:
        Tuple of (is_valid, error_message)
    """

    try:
        yaml.safe_load(content)
        return True, None
    except yaml.YAMLError as e:
        return False, str(e)
    except Exception as e:
        return False, f"Unexpected error: {e}"
