"""
Game Engine Module

This module provides the core game engine components for the Space Hulk text adventure game.
It includes data models for game state, scenes, entities, command parsing, actions, and the
main game engine with persistence.

The engine is designed to load and execute games generated by the CrewAI agents, providing
a playable text adventure interface.
"""

from .game_state import GameState
from .scene import Scene
from .entities import Item, NPC, Event
from .parser import CommandParser
from .actions import (
    Action,
    MoveAction,
    TakeAction,
    DropAction,
    UseAction,
    LookAction,
    InventoryAction,
    TalkAction,
    HelpAction,
    UnknownAction,
)
from .engine import TextAdventureEngine
from .persistence import (
    save_game,
    load_game,
    get_save_metadata,
    list_save_files,
    delete_save,
    PersistenceError,
)
from .game_data import GameData
from .loader import ContentLoader, LoaderError, YAMLParseError, ValidationError
from .validator import GameValidator, ValidationResult

__all__ = [
    'GameState',
    'Scene',
    'Item',
    'NPC',
    'Event',
    'CommandParser',
    'Action',
    'MoveAction',
    'TakeAction',
    'DropAction',
    'UseAction',
    'LookAction',
    'InventoryAction',
    'TalkAction',
    'HelpAction',
    'UnknownAction',
    'TextAdventureEngine',
    'save_game',
    'load_game',
    'get_save_metadata',
    'list_save_files',
    'delete_save',
    'PersistenceError',
    'GameData',
    'ContentLoader',
    'LoaderError',
    'YAMLParseError',
    'ValidationError',
    'GameValidator',
    'ValidationResult',
]
