"""
Game Engine Module

This module provides the core game engine components for the Space Hulk text adventure game.
It includes data models for game state, scenes, entities, command parsing, and actions.

The engine is designed to load and execute games generated by the CrewAI agents, providing
a playable text adventure interface.
"""

from .game_state import GameState
from .scene import Scene
from .entities import Item, NPC, Event
from .parser import CommandParser
from .actions import (
    Action,
    MoveAction,
    TakeAction,
    DropAction,
    UseAction,
    LookAction,
    InventoryAction,
    TalkAction,
    HelpAction,
    UnknownAction,
)

__all__ = [
    'GameState',
    'Scene',
    'Item',
    'NPC',
    'Event',
    'CommandParser',
    'Action',
    'MoveAction',
    'TakeAction',
    'DropAction',
    'UseAction',
    'LookAction',
    'InventoryAction',
    'TalkAction',
    'HelpAction',
    'UnknownAction',
]
