"""
Game Engine Module

This module provides the core game engine components for the Space Hulk text adventure game.
It includes data models for game state, scenes, entities, command parsing, actions, and the
main game engine with persistence.

The engine is designed to load and execute games generated by the CrewAI agents, providing
a playable text adventure interface.
"""

from .actions import (
    Action,
    DropAction,
    HelpAction,
    InventoryAction,
    LookAction,
    MoveAction,
    TakeAction,
    TalkAction,
    UnknownAction,
    UseAction,
)
from .engine import TextAdventureEngine
from .entities import NPC, Event, Item
from .game_data import GameData
from .game_state import GameState
from .loader import ContentLoader, JSONParseError, LoaderError, ValidationError, YAMLParseError
from .parser import CommandParser
from .persistence import (
    PersistenceError,
    SaveSystem,
    delete_save,
    get_save_metadata,
    list_save_files,
    load_game,
    save_game,
)
from .scene import Scene
from .validator import GameValidator, ValidationResult

__all__ = [
    "NPC",
    "Action",
    "CommandParser",
    "ContentLoader",
    "DropAction",
    "Event",
    "GameData",
    "GameState",
    "GameValidator",
    "HelpAction",
    "InventoryAction",
    "Item",
    "JSONParseError",
    "LoaderError",
    "LookAction",
    "MoveAction",
    "PersistenceError",
    "SaveSystem",
    "Scene",
    "TakeAction",
    "TalkAction",
    "TextAdventureEngine",
    "UnknownAction",
    "UseAction",
    "ValidationError",
    "ValidationResult",
    "YAMLParseError",
    "delete_save",
    "get_save_metadata",
    "list_save_files",
    "load_game",
    "save_game",
]
